-- Hello, source explorers!
--
-- You've found the lua folder, I've made use of Lua in this codebase because
-- if we're being honest, it's just really good and productive. You'll notice
-- that there is a lot here, and a lot to take in, and I get that, don't worry.
-- I've provided lots of comments in the files, and have documentation up on
-- this games source code repository: https://github.com/embedded-nerdgirl/neon-dreams
--
-- If you want to mod this game, please use the 'assets/mods' directory and not this.
-- If these break, the game will have degraded functionality or may just stop working
-- altogether. If you want to mod these anyway, please remember to make a backup of
-- the working code before you do so. And if things break badly, you can always use
-- Steam to validate the integrity of the game files, which should automatically fix
-- any and all issues you may have.